# .github/workflows/sonar-snyk.yml
name: Code Quality Pipeline

on:
  push:
    branches: [ main ]
 
jobs:
  scan:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------------
      # PYTHON SETUP ✅
      # -------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      # -------------------------------
      # SONAR (BLOCKING)
      # -------------------------------
      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=.
            -Dsonar.host.url=http://13.235.132.100:9000
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # -------------------------------
      # SNYK (PYTHON) ✅
      # -------------------------------
      - name: Snyk Scan
        uses: snyk/actions/python@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
